# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Arian Naseh
title: Data Scientist, Machine Learning Engineer
email: a.nasehzade@gmail.com
website: ariannsz.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: arianNsz
github_username: arianNsz
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: arian-naseh
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
additional_links:
  - title: Medium
    icon: fab fa-medium
    url: https://medium.com/@arian.naseh
  - title: Google Scholar
    icon: fas fa-graduation-cap
    url: https://scholar.google.com/citations?hl=en&user=smpsVvcAAAAJ

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile2024.png
about_content: | # this will include new lines to allow paragraphs
  Hi! I'm Arian, and I'm obsessed with turning complex data into awesome machine learning solutions. With four years of experience in finance and advertising under my belt, I've got a knack for building predictive models, wrangling data pipelines, and playing with the latest LLM magic. From my earlier adventures in IoT and deep reinforcement learning research to real-world projects in risk management, productivity tools, and ad targeting, I love the challenge of bringing ML ideas to life. Want to see what I've been up to? Check out my portfolio, Medium articles, or LinkedIn profile. If you're building cool stuff with data, let's connect - you can find me on LinkedIn or shoot me an email at a.nasehzade@gmail.com!
  
  Cheers!
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: A Deep Reinforcement Learning-Based Caching Strategy For IoT Networks With Transient Data
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          #TensorFlow   #Keras   #StableBaseline   #DRL   #openai #gym    #A2C #PPO   #numpy   #pandas   #matplotlib
        description: | # this will include new lines to allow paragraphs
          This project, which led to a couple of publications, was my master's thesis project. I have deployed a couple of DRL algorithms such as A2C and PPO to address the caching problem in IoT networks where files have a limited lifetime. We improved the cache hit rate and energy consumption of the network significantly.

  - title: Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research and Teaching Assitant
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: York University
        caption: Sep. 2019 - Present
        description: | # this will include new lines to allow paragraphs
          Aside from the thesis project (mentioned above), I was the teaching assistant for multiple courses. I helped students to develop and debug Android applications using Java and XML for one semester. I also taught MATLAB programming and helped students with code debugging for another class.

      - layout: left
        title: Researcher
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: York University
        caption: Jan. 2019 - Sep. 2019
        description: | # this will include new lines to allow paragraphs
          Before starting the M.Sc program, I had a research contract with my supervisor, Dr. Ping Wang. Since she hadn't had any grad student at York University until then, we needed to develop a research road map for the team she was recruiting at the time. We find credible resources to study DRL. After doing an extensive literature review, we found a couple of interesting problems that we thought DRL could effectively address, such as caching in computer networks and routing in unmanned aerial vehicles (UAV) networks. We also briefly studied federated learning and its use cases, which later became the research area for our other group members.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: York University
        caption: 2019 - 2021
        sub_title: M.Sc Computer Science
        description: | # this will include new lines to allow paragraphs
          During the M.Sc program, I  focused my studies on machine learning and data science. I took courses on machine learning theory, data mining, advance deep neural network, data visualization, and more. My thesis is about the application of Deep Reinforcement Learning in IoT networks.

      - layout: left
        title: Amirkabir University of Technology
        caption: 2016 - 2018
        sub_title: M.Sc Digital Electronics
        description: | # this will include new lines to allow paragraphs
          This program helped me to distance my studies from electrical engineering and pivot towards computer science. I took courses in bio-inspired artificial intelligence and statistical learning, which got me hooked on machine learning readings for the years to come.

      - layout: left
        title: University of Guilan
        caption: 2011 - 2016
        sub_title: B.Sc Electrical Engineering - Electronics
        description: | # this will include new lines to allow paragraphs
          I received my bachelor's degree from the University of Guilan, in the beautiful city of Rasht, Iran.  I did some TAship for electronics courses. For my final project, I designed an LED lamp driver and developed an android application to control the lamp's brightness.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data science and machine learning, I often find myself busy with one of the followings in my free time:
      - Doing some small investments and following business news (I love this one!)
      - Gaming
      - Binge-watching Netflix
      - Binge-listening a podcast

#       Look at this cool image
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
